### ISSUE TITLE
interactive annotation & install ImageJ plugin

### ISSUE THREAD

**Issue by hw-ju** [nadeemlab/ImPartial#11]
Hi there! 
Really appreciate you put much effort in building ImPartial!

I want to try out ImPartial on my digital pathology data, especially want to use the interactive annotation feature. Is this feature available now or is still under active development?

I'm following the [Monai-label and Impartial Integration](https://github.com/nadeemlab/ImPartial#monai-label-and-impartial-integration) to set up everything. In [Client - Install ImageJ plugin](https://github.com/nadeemlab/ImPartial#client---install-imagej-plugin), the command `git checkout feat/imagej-plugin` outputs `error: pathspec 'feat/imagej-plugin' did not match any file(s) known to git`, and from `git branch -a` it seems this branch is not there. 

Besides, I can't find the `impartial_imagej-0.1.jar` used in:
```
Copy the latest build imagej plugin from 'ImPartial/imagej-plugintarget/impartial_imagej-0.1.jar' to '/Applications/Fiji.app/plugins'
```

**Comment by ricdodds** [comment]
Hi @hw-ju, thanks for pointing this out. The Fiji plugin is ready to use, and feedback is very welcome. In order to install it please follow the instructions [here](https://github.com/nadeemlab/ImPartial#imagejfiji-plugin). The ones you posted were updated and I already removed them from the README.

After running `mvn clean package` you should be able to find the jar file under the `target/` directory and run
```shell
cp target/impartial_imagej-0.1.jar /Applications/Fiji.app/plugins
```

Please let us know if you find any issues.

**Comment by hw-ju** [comment]
@ricdodds Thanks for your help! I can open ImPartial plugin within Fiji now :)
