### ISSUE TITLE
How to start from weak annotations in numpy arrays? 

### ISSUE THREAD

**Issue by OmarAshkar** [nadeemlab/ImPartial#21]
Hello,

I am interested in ImPartial, not sure if it will solve my problem. I found the documentation alittle bit difficult to follow, so I appreciate if there is a recommended workflow. 

I have weak annotations make by color thresholding for bright field images. I am try to enhance these labels. Can I use them as input instead of scribbles? Also, can will I interact with the output after that?

Thanks in advance!

**Comment by sanadeem** [comment]
Thank you for your comment. Sorry, we are still finalizing the framework and hence, the delay in more accessible documentation. Yes, you can use the thresholded images as input/starting point given it matches our definition of "scribbles" in our Fiji plugin. You might have to run connected component analysis to remove any "noisy" scribbles in this case (random noise because of your thresholding). Given our interactive/iterative active learning framework available via Fiji plugin, yes you will be able to interact with the output after that iteratively and refine the results till you are satisfied.

We will update the details soon for the official release of this tool (hopefully in another 2-3 weeks).

Thanks again for your interest.
